### ISSUE TITLE
Custom fonts broken when publishing PDF

### ISSUE THREAD

**Issue by mindyou** [docToolchain/docToolchain#336]
**Describe the bug**
Publication to PDF fails when documents use custom fonts in the documentation directory. It has worked in a version that I did not upgrade for a long time but when I just upgraded, it started failing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a document with a custom font in "${docDir}/fonts"
2. Publish to PDF (doctoolchain . generatePDF -PmainConfigFile=Config.groovy)
3. Error message: 16:23:36.197 [ERROR] [org.asciidoctor.internal.JRubyAsciidoctor] (ArgumentError) uri:classloader://gems/asciidoctor-pdf-1.5.0.alpha.15/data/fonts/FrutigerNextPro-Regular.ttf not found

**Expected behavior**
A working conversion to PDF

**Screenshots**
NA

**Configuration**
 - OS: Mac
 - Browser NA
 - Relevant SDK Versions NA

**Additional context**
Can be fixed by applying this patch:

diff --git a/scripts/AsciiDocBasics.gradle b/scripts/AsciiDocBasics.gradle
index 2f36461..06f8126 100755
--- a/scripts/AsciiDocBasics.gradle
+++ b/scripts/AsciiDocBasics.gradle
@@ -77,6 +77,7 @@ tasks.withType(org.asciidoctor.gradle.AsciidoctorTask) { docTask ->
     attributes  (
             'pdf-stylesdir': "${pdfThemeDir}@",
             'pdf-style': 'custom@',
+            'pdf-fontsdir': "${docDir}/fonts",
             'source-highlighter': 'coderay@',
             'imagesdir': 'images@',
             'toc': 'left@',

**Comment by rdmueller** [comment]
thanx for your patience.
As I can see, you've added a fix as patch. 
Could you create a PR from it?

Thanx!

**Comment by mindyou** [comment]
I am fine creating a PR for that little patch but I wonder if a test needs to be added? I haven't looked into the automated tests of docToolchain yet.

**Comment by rdmueller** [comment]
The automated tests are not as good as they could be and hard to write...
So I am fine with the PR...

**Comment by mindyou** [comment]
OK, I will make one tomorrow

**Comment by rdmueller** [comment]
sorry, I have just reverted the changes of your PR (not the PR itself) because it breaks the tests.
With the cutom `fontsDir`, the system will not find the default fonts anymore.

Can you do me a favour and check if you can set the `fontsDir` directly in your document as attribute?

```
:pdf-fontsdir: fonts
```
This could also work. I usually have a `config.adoc` with such settings which I include from each document.

**Comment by joel-loewenstein** [comment]
Hello,
i just installed docToolchain according to documentation using the git clone method. 

Then i created serveral new doc folders. One including the standard init for Arc42 in German with Help. One other in English with Help. For that one i worked to create a custom-theme adaptation so that non build in fonts shall be used similar to the html output using the asciidoctor skin. e.g. open sans font. 

I stumbled accross the same issue that the build in fonts cannot be found anymore. In my experience both declarations of the fonts folder that you described worked successfully to set the fonts folder: 

`'pdf-fontsdir': "fonts@",` and `'pdf-fontsdir': "${docDir}/fonts",`

In both cases the content of the confic.adoc was ignored. I created another issue recently that describes a variable being set in config.adoc not working in a comparable way. See #533 

So it seems there is the need for a broader fix to get config.adoc content being applied so that a local fix in the AsciiDocBasics.gradle file shall be avoidable.

**Comment by joel-loewenstein** [comment]
After some thinking without looking at code, it seems to me that the path is replaced when `'pdf-fontsdir'` is set, instead of appending it to `GEM_FONTS_DIR` . Do you know where this happens? 

Admittedly i am a bit overwhelmed to analyse docToolchain in full. I would appreciate a hint where to look into... i find it odd, that this shall have worked in a previous release. So quite unsure if one of the external components changed its behaviour or some internal scripting was changed between mentioned releases.

@mindyou which was the previous release that worked for you before the upgrade?

**Comment by joel-loewenstein** [comment]
To resolve the missing fonts from the default theme once the `'pdf-fontsdir' is set, i downloaded them from the github repo into the local specifier folder so that i could actually build the pdf. 

After that i found this info in the theme documentation: [Extending the Font catalog](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#extending-the-font-catalog)

It says if you are not extending and merging it is normal that the fonts have to be redeclared:

extends: default
>font:
>  catalog:
>    Noto Serif:
>      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
>      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
>      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
>      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf

I tried using `GEM_FONTS_DIR`and it worked, i could omit to download them locally. I noticed that the custom theme seems not to extend the default theme and that it would be the reason why to redeclare.

**Comment by joel-loewenstein** [comment]
@rdmueller do you get notified about this issue or only if i mention you directly as it was tagged wontfix by @stalebot ?

**Comment by rdmueller** [comment]
the "wontfix" was a mistake - I wasn't aware that stalebot adds those wontfix labels immediatly.
AFAIK, I get always notified - the label is just a label and does not change notifications :-)

**Comment by rdmueller** [comment]
So, @joel-loewenstein - do you suggest that we should update https://github.com/docToolchain/docToolchain/blob/master/src/docs/pdfTheme/custom-theme.yml ?

**Comment by joel-loewenstein** [comment]
Yes, i think we shall update the custom theme in agreement with the arc42 authors to fit the html style and fix the footer and header issue and get a likewise style accross all types of derived artifacts.

HTML | PDF | Word
------|------|-------
![image](https://user-images.githubusercontent.com/4130973/108767854-3f53e780-7557-11eb-8caa-3afd488370a3.png) | ![image](https://user-images.githubusercontent.com/4130973/108767901-4bd84000-7557-11eb-967b-757f7d2e1094.png) | ![image](https://user-images.githubusercontent.com/4130973/108767930-54307b00-7557-11eb-94ae-3cfd3f1ddfd4.png)

But i am still working on understanding theming and its dependencies in asciidoctor-pdf ... i would suggest then a standardized look and feel. But why the header and footer is not rendered i presume i need your expertise.

What i did so far:
I first copied all fonts of my interest (open sans, noto sans, roboto, source sans pro, gilroy) into the fonts folder, then set the folder, stumbled across the above mentioned issue. Then i copied all default fonts into the fonts folder to be able to build the PDF and played around to get this:

TOC | Body
-----|-----
![image](https://user-images.githubusercontent.com/4130973/108769980-0d905000-755a-11eb-9445-aba9428da415.png) | ![image](https://user-images.githubusercontent.com/4130973/108770004-17b24e80-755a-11eb-825d-9f5d35ed624b.png)


Then added the keyword `GEM_FONTS_DIR` and tried without locally copied fonts, seems successful, then in the next step i realized that the m+ is a sans font already and that it might be good enough instead of adding the open sans font.

But i copied the fonts used in the html style... so still quite some investigations to do. My goal would be to have it as slim as possible while looking most similar to the html style.

Also the themeing guide mentiones the extend function, which i still would want to test out.


The current result starts to look like the HTML but still needs some additional work, as you see in the help section.

**Comment by joel-loewenstein** [comment]
I read through the pdf-theming guide and understood, when merging the catalogs, it should be sufficient to set `merge: true` to still have the build in fonts available and only extend it by one desired font.

With dtcw and ng i did a test: installed newly, there is when choosing to install arc42DE no custom-theme.yml copied. So i created one to just get a TOC and Colors adjusted using build in fonts only, which worked for the font and color but not for header and footer (again):

```
header:
  height: 0.75in
  line_height: 1
  recto_content:
    center: '{document-title}'
  verso_content:
    center: '{document-title}'
footer:
  height: 0.75in
  line_height: 1
  recto_content:
    right: '{chapter-title} | *{page-number}*'
  verso_content:
    left: '*{page-number}* | {chapter-title}'
```

TOC | Document
-----|-----------
![image](https://user-images.githubusercontent.com/4130973/109271269-94ba1e00-780f-11eb-8f1e-8817af938ff8.png) | ![image](https://user-images.githubusercontent.com/4130973/109271353-aef3fc00-780f-11eb-8448-11006412d5f1.png)

I then added one font and the fonts dir, enabled fonts dir in AsciiDocBasics.gradle with 
`'pdf-fontsdir': "${docDir}/fonts",` and set `merge: true` 
and expected that header and footer do not work, but the font changes. Instead i got again a font not found error.

```
> Task :generatePDF
Converting /Users/jlo2k/Repository/git/arc42DE/src/docs/arc42/arc42.adoc
could not locate or load the pdf theme `custom in /Users/jlo2k/Repository/git/arc42DE/pdfTheme because of Psych::SyntaxError (/Users/jlo2k/Repository/git/arc42DE/pdfTheme/custom-theme.yml): expected <block end>, but found <block mapping start> while parsing a block mapping at line 15 column 5; reverting to default theme
(ENOENT) No such file or directory - notoserif-regular-subset.ttf not found in /Users/jlo2k/Repository/git/arc42DE/fonts
```
I guess i have to dig deeper with debug to understand how it acutally works.

**Comment by joel-loewenstein** [comment]
i am confused right now, it seems with the current setup the `extends:`keyword wihtin a style does not have any effect. do you know something about that? was that the reason why the custom-theme.yml was not extending?

**Comment by rdmueller** [comment]
I hope that the dtcw approach does not introduce some of the confusion...
btw: i fixed something for dtcw yesterday. you can now do a `./dtcw copyThemes` and thus get a copy of the internal pdfTheme copied to your project.

btw: I don't think that the current setup might be the reason that things like `extends:` do not work. My experience is that the pdf styling is a bit brittle and hard to get right. That's why I only change basic thing in the theme like headline color, header and footer.

A colleague managed to `extend` the theme. I will point him at these issues on monday. Maybe he can help.

**Comment by joel-loewenstein** [comment]
just to be sure i will do a test with the current master branch... 
i assume i can just set the version to master in dtcw? 
then there should be no difference to manual instructions in the documentation in regards to the behaviour of docToolchain?

**Comment by joel-loewenstein** [comment]
i had to include the `GEM_FONTS_DIR` in 
`pdf-fontsdir:GEM_FONTS_DIR;/Users/myuser/myrepository/arc42DE/src/res/fonts@`
i am certain i did not do that when in commented 6 days ago... it puzzles me a bit though... have not kept the logs..
also because default is already using the keyword.
i also modified the doc a bit, but have a look at the output.
[arc42.pdf](https://github.com/docToolchain/docToolchain/files/6055392/arc42.pdf)

**Comment by joel-loewenstein** [comment]
you notice i played around with the directories a little bit...

**Comment by joel-loewenstein** [comment]
i would love though that we extend the `--info` logging by a few important attributes.
i also understood that asciidoctor-pdf and the document interact in a way that `...@`allows the doc to set this variable and i would love to see the attributes when  altered by the converter as with `:pdf-theme:` 
it seems it cannot reside in `confic.adoc` but others can so not yet fully understood yet
but if that option get the converter to output this info would be great... even with `--debug` i do not see it currently

**Comment by joel-loewenstein** [comment]
so in short i got custom fonts going with extends on V ng.
Still have to verify master though... but i would not expect a totally different behaviour.

**Comment by joel-loewenstein** [comment]
i have now chosen to extend from the [default-with-fallback-font-theme.yml theme](https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-with-fallback-font-theme.yml) of the build in [themes](https://github.com/asciidoctor/asciidoctor-pdf/tree/master/data/themes) it in itself extends from default.

here is my current theme that led to the pdf above (directories are non dtc std):
```
extends: default-with-fallback-font
font:
  catalog:
    merge: true

    # Open Sans
    Open Sans:
        light: opensans-light.ttf
        normal: opensans-regular.ttf
        bold: opensans-bold.ttf
        italic: opensans-italic.ttf
        bold_italic: opensans-bolditalic.ttf
        light_italic: opensans-lightitalic.ttf

page:
  margin: [0.7in, 0.67in, 0.67in, 0.67in]

toc:
  font_family: Open Sans
  font_color: 2156A5
  font_style: normal
  font_size: $base_font_size_large

heading:
  font_family: Open Sans
  font_style: light
  font_color: BA3925

header:
  font_family: Open Sans
  font_style: light
  height: $base_line_height_length * 3.5
  border_color: dddddd
  border_width: 0.25
  recto:
    left:
      content: image:../../docs/arc42/images/arc42-logo.png[width=50]
    center:
      content: 'arc42 Template'
    right:
      content: image:../../docs/arc42/images/company-logo.png[width=70]
  verso:
    left:
      content: $header_recto_left_content
    center:
      content: $header_recto_center_content
    right:
      content: $header_recto_right_content

footer:
  font_family: Open Sans
  font_style: light
  recto:
    right:
      content: '{section-title} | *{page-number}*'
  verso:
    left:
      content: '*{page-number}* | {section-title}'
```
