### ISSUE TITLE
Header and Footer settings from custom-theme are not generated as expected

### ISSUE THREAD

**Issue by joel-loewenstein** [docToolchain/docToolchain#537]
## Describe the bug

After clean install and init of Arc42EN i use generatePDF task and find the following desired configuration content is **NOT** rendered into the PDF(see also Screenshot below):
.docDir/pdfTheme/custom-theme.yml extract as delivered with docToolchain:
```
header:
  height: 0.75in
  line_height: 1
  recto_content:
    center: '{document-title}'
  verso_content:
    center: '{document-title}'
footer:
  height: 0.75in
  line_height: 1
  recto_content:
    right: '{chapter-title} | *{page-number}*'
  verso_content:
    left: '*{page-number}* | {chapter-title}'
```

## To Reproduce
1. Follow installation according to docs [2.1 get the tool](https://doctoolchain.github.io/docToolchain/#_get_the_tool), Linux with git clone method
2. Init according to [2.2.2 arc42 from scratch](https://doctoolchain.github.io/docToolchain/#_arc42_from_scratch):
    
    `./gradlew -b init.gradle initArc42EN -PnewDocDir=../CleanArc42EN`

3. Create according to [2.3 Build](https://doctoolchain.github.io/docToolchain/#_build):
    
    ```
    cd ../CleanArc42EN
    docToolchain . generatePDF
    .
    .
    BUILD SUCCESSFUL in 15s
    1 actionable task: 1 executed
    ```
4. Open the created output file arc42-template.pdf within a reader to your liking, find see the expected footer and header informations are missing described in the screenshot on any given page of the PDF.

## Expected behavior
The mentioned content shall be rendered into the PDF by the processor like on the example blog page [Customization of Asciidoctor PDF output](https://www.wimdeblauwe.com/blog/2019/2019-12-20-customization-of-asciidoctor-pdf-output/) shown in the second screenshot.

## Screenshots

Screenshot of Template generated: 
![image](https://user-images.githubusercontent.com/4130973/108631558-c5decb00-746a-11eb-8f52-2b5b5ee50039.png)

Screenshot from Blog Site:

![image](https://www.wimdeblauwe.com/images/2019/10/image-5.png)

## Configuration
```
docToolchain . --version
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.15.7 x86_64
```
## Additional context
I did a short test on a windows vm to ensure that it is not some misconfiguration or mac based behaviour. Output was similarly missing the expected header and footer content.
