### ISSUE TITLE
Wrong classes in default custom-theme.yml

### ISSUE THREAD

**Issue by houserockr** [docToolchain/docToolchain#568]
Unfortunately, asciidoctor changed some class names.
The following lines in the default yaml theme don't work any more:

```
footer:
   height: 0.75in
   line_height: 1
   recto_content:
     right: '{chapter-title} | *{page-number}*'
   verso_content:
     left: '*{page-number}* | {chapter-title}'
```
This is how it should look like:
```
footer:
   height: 0.75in
   line_height: 1
   recto:
     right: 
       content: '{chapter-title} | *{page-number}*'
   verso:
     left: 
      content: '*{page-number}* | {chapter-title}'
```
Just in case anyone else is having trouble.
Update: Same applies to the header.
